#!/usr/bin/env python


#「rospy」モジュールを使用する準備をする
import rospy
#クラス名RotatedRectStampedのみで使用できるようにする
from opencv_apps.msg import RotatedRectStamped
#クラス名ImageMarker2のみで使用できるようにする
from image_view2.msg import ImageMarker2
#クラス名Pointのみで使用できるようにする
from geometry_msgs.msg import Point
def cb(msg):
　　　　　　　　#msg.rectを出力する
	print msg.rect
　　　　 　　　#トピック
	marker = ImageMarker2()
	#値代入
	marker.type = 0                
	marker.position = Point(msg.rect.center.x, msg.rect.center.y,0)
　　　　　　　　#トピック（/image_marker）にメッセージを配信する
	pub.publish(marker)

#rospyにノード名clientを通知してMasterと通信できるようにする
rospy.init_node('client')

#/camshift/track_boxというトピックが更新されたときに関数cbを呼ぶ
rospy.Subscriber('/camshift/track_box', RotatedRectStamped, cb)

#/image_markerというトピックにImageMarker2というメッセージのタイプで送ることを宣言
pub = rospy.Publisher('/image_marker', ImageMarker2)

#コールバックによりノードが終了しないようにする
rospy.spin()
