controller_list:
  - name: fake_mainpulator_controller
    joints:
      - arm_link1_joint
      - arm_link2_joint
      - arm_link3_joint
      - arm_link4_joint
      - arm_link5_joint
      - arm_link6_joint
      - arm_link7_joint