joint_name_to_servo_id: {
  head_joint0: {id: 32, direction: -1, offset: 0},
  head_joint1: {id: 34, direction: -1, offset: 0},
  rarm_joint0: {id: 0, direction: 1, offset: 0},
  rarm_joint1: {id: 2, direction: 1, offset: 0},
  rarm_joint2: {id: 4, direction: 1, offset: 0},
  rarm_joint3: {id: 6, direction: 1, offset: 0},
  rarm_joint4: {id: 8, direction: 1, offset: 0},
  rarm_joint5: {id: 10, direction: 1, offset: 0},
  rarm_joint6: {id: 12, direction: -1, offset: 0},
  rarm_gripper_joint: {id: 14, direction: -1, offset: 0},
  larm_joint0: {id: 1, direction: 1, offset: 0},
  larm_joint1: {id: 3, direction: 1, offset: 0},
  larm_joint2: {id: 5, direction: 1, offset: 0},
  larm_joint3: {id: 7, direction: -1, offset: 0},
  larm_joint4: {id: 9, direction: 1, offset: 0},
  larm_joint5: {id: 11, direction: 1, offset: 0},
  larm_joint6: {id: 13, direction: -1, offset: 0},
  larm_gripper_joint: {id: 15, direction: 1, offset: 0},
  front_right_wheel_joint: {id: 20, direction: 1, offset: 0, type: continuous},
  front_left_wheel_joint: {id: 21, direction: -1, offset: 0, type: continuous},
  rear_right_wheel_joint: {id: 22, direction: 1, offset: 0, type: continuous},
  rear_left_wheel_joint: {id: 23, direction: -1, offset: 0, type: continuous},
}
